import { Inter } from "next/font/google";
import "./globals.css";

import { Header, FooterJSX } from "../components";
import { Flowbite } from "flowbite-react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Cinemate",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <Flowbite>
      <html lang="en">
        <body className={inter.className}>
          <Header />

          {children}
          <FooterJSX />
        </body>
      </html>
    </Flowbite>
  );
}
